#!/usr/bin/env bash
# Shared local-stack environment settings.
# Source this file from scripts/start_local_stack.sh and optionally from your shell.

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"

RUN_DIR="$ROOT_DIR/.local_stack"
DATA_ROOT="$ROOT_DIR/data"
ARTIFACT_ROOT="$DATA_ROOT/artifacts"
ARTIFACT_AUDIO_ROOT="$ARTIFACT_ROOT/audio"
MEMORY_DB_PATH="$DATA_ROOT/sqlite/memory.db"
ASSET_CATALOG_PATH="$DATA_ROOT/assets/catalog.json"

if [[ -x "/home/zodrak/.pyenv/versions/py312/bin/python" ]]; then
  PYTHON_BIN="/home/zodrak/.pyenv/versions/py312/bin/python"
else
  PYTHON_BIN="python"
fi

PYTHONPATH="$ROOT_DIR"

MCP_TRANSPORT="sse"
MCP_HOST="0.0.0.0"

MCP_ASSETS_HOST="0.0.0.0"
MCP_ASSETS_PORT="7101"
MCP_ASSETS_PATH="/mcp"

MCP_MEMORY_HOST="0.0.0.0"
MCP_MEMORY_PORT="7102"
MCP_MEMORY_PATH="/mcp"

MCP_XTTS_HOST="0.0.0.0"
MCP_XTTS_PORT="7203"
MCP_XTTS_PATH="/mcp"

MCP_LIPSYNC_HOST="0.0.0.0"
MCP_LIPSYNC_PORT="7104"
MCP_LIPSYNC_PATH="/mcp"

MCP_RENDER_HOST="0.0.0.0"
MCP_RENDER_PORT="7105"
MCP_RENDER_PATH="/mcp"

MCP_QC_HOST="0.0.0.0"
MCP_QC_PORT="7106"
MCP_QC_PATH="/mcp"

XTTS_URL="http://127.0.0.1:${MCP_XTTS_PORT}${MCP_XTTS_PATH}"
MCP_ASSETS_URL="http://127.0.0.1:${MCP_ASSETS_PORT}${MCP_ASSETS_PATH}/sse"
MCP_MEMORY_URL="http://127.0.0.1:${MCP_MEMORY_PORT}${MCP_MEMORY_PATH}/sse"
MCP_LIPSYNC_URL="http://127.0.0.1:${MCP_LIPSYNC_PORT}${MCP_LIPSYNC_PATH}/sse"
MCP_RENDER_URL="http://127.0.0.1:${MCP_RENDER_PORT}${MCP_RENDER_PATH}/sse"
MCP_QC_URL="http://127.0.0.1:${MCP_QC_PORT}${MCP_QC_PATH}/sse"

VLLM_HOST="0.0.0.0"
VLLM_PORT="8000"
VLLM_MODEL="Qwen/Qwen2.5-3B-Instruct-AWQ"
VLLM_QUANTIZATION="awq"
VLLM_MAX_MODEL_LEN="8192"
VLLM_GPU_MEMORY_UTILIZATION="0.5"
VLLM_START_TIMEOUT_SEC="300"
VLLM_HF_HOME="$DATA_ROOT/vllm-cache"
VLLM_HF_HUB_CACHE="$DATA_ROOT/vllm-cache/hub"
VLLM_TRANSFORMERS_CACHE="$DATA_ROOT/vllm-cache/transformers"
VLLM_DOWNLOAD_DIR="$VLLM_HF_HUB_CACHE"
VLLM_BASE_URL="http://127.0.0.1:${VLLM_PORT}/v1"

LLM_MODEL="Qwen/Qwen2.5-3B-Instruct-AWQ"
LLM_MAX_TOKENS="3200"
LLM_TIMEOUT_SEC="180"
FINAL_MIN_MOTION_DIFF="0.15"

CRITIC_GATE_ENABLED="1"
CRITIC_PASS_SCORE="50"
CRITIC_MAX_ROUNDS="3"

XTTS_DEVICE="cuda"
XTTS_MODEL="tts_models/multilingual/multi-dataset/xtts_v2"
XTTS_LANGUAGE="en"
XTTS_SPEAKER_WAV_DIR="$DATA_ROOT/tts/speakers"
TTS_HOME="$DATA_ROOT/tts-home"
XDG_CACHE_HOME="$DATA_ROOT/tts-cache"
HF_HOME="$DATA_ROOT/tts-cache/hf"
HF_HUB_CACHE="$DATA_ROOT/tts-cache/hf/hub"
TRANSFORMERS_CACHE="$DATA_ROOT/tts-cache/hf/transformers"
COQUI_TOS_AGREED="1"

WAV2LIP_SCRIPT="$DATA_ROOT/models/Wav2Lip/inference.py"
WAV2LIP_CHECKPOINT="$DATA_ROOT/models/Wav2Lip/checkpoints/wav2lip_gan.pth"
NUMBA_CACHE_DIR="/tmp/numba_cache"

export ROOT_DIR RUN_DIR DATA_ROOT ARTIFACT_ROOT ARTIFACT_AUDIO_ROOT MEMORY_DB_PATH ASSET_CATALOG_PATH
export PYTHON_BIN PYTHONPATH
export MCP_TRANSPORT MCP_HOST
export MCP_ASSETS_HOST MCP_ASSETS_PORT MCP_ASSETS_PATH
export MCP_MEMORY_HOST MCP_MEMORY_PORT MCP_MEMORY_PATH
export MCP_XTTS_HOST MCP_XTTS_PORT MCP_XTTS_PATH
export MCP_LIPSYNC_HOST MCP_LIPSYNC_PORT MCP_LIPSYNC_PATH
export MCP_RENDER_HOST MCP_RENDER_PORT MCP_RENDER_PATH
export MCP_QC_HOST MCP_QC_PORT MCP_QC_PATH
export XTTS_URL MCP_ASSETS_URL MCP_MEMORY_URL MCP_LIPSYNC_URL MCP_RENDER_URL MCP_QC_URL
export VLLM_HOST VLLM_PORT VLLM_MODEL VLLM_QUANTIZATION VLLM_MAX_MODEL_LEN VLLM_GPU_MEMORY_UTILIZATION VLLM_START_TIMEOUT_SEC VLLM_HF_HOME VLLM_HF_HUB_CACHE VLLM_TRANSFORMERS_CACHE VLLM_DOWNLOAD_DIR VLLM_BASE_URL
export LLM_MODEL LLM_MAX_TOKENS LLM_TIMEOUT_SEC
export FINAL_MIN_MOTION_DIFF
export CRITIC_GATE_ENABLED CRITIC_PASS_SCORE CRITIC_MAX_ROUNDS
export XTTS_DEVICE XTTS_MODEL XTTS_LANGUAGE XTTS_SPEAKER_WAV_DIR TTS_HOME XDG_CACHE_HOME HF_HOME HF_HUB_CACHE TRANSFORMERS_CACHE COQUI_TOS_AGREED
export WAV2LIP_SCRIPT WAV2LIP_CHECKPOINT NUMBA_CACHE_DIR
